type Coordinate {
  latitude: Float!
  longitude: Float!
}

enum Day {
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
  SUNDAY
}

type DateTime {
  day: Day
  timestamp: Date
}

type PlotterPoint {
  location: Coordinate!
  time: DateTime!
}

type PlotterData {
  points: [PlotterPoint]
}
